[staticAssets]
"servers.yaml" = '''
servers:
  - namespace: httpbin
    name: httpbin
    url: https://raw.githubusercontent.com/conorbranagan/mcp-openapi/refs/heads/main/test-specs/httpbin.yaml
    base_url: https://httpbin.org
    paths:
      - /get
      - /status
      - /ip
      - /headers
      - /user-agent
'''

[start]
  cmd = "python main.py --config /assets/servers.yaml"