[staticAssets]
"servers.yaml" = '''
servers:
  - namespace: stripe
    # Define headers to forward to the server
    headers:
      - Authorization
    # This is the name as it appears to the LLM
    name: Stripe API
    url: https://raw.githubusercontent.com/stripe/openapi/refs/heads/master/openapi/spec3.yaml
    base_url: https://api.stripe.com
    # Select which API paths to expose over MCP
    paths:
      - /v1/customers$

  - namespace: httpbin
    name: httpbin
    url: file://test-specs/httpbin.yaml
    base_url: https://httpbin.org
    paths:
      - /get
      - /status
      - /ip
      - /headers
      - /user-agent

  # - namespace: zendesk
  #   name: Zendesk API
  #   url: file://apis/zendesk-oas.yaml
  #   base_url: https://api.zendesk.com
  #   paths:
  #     - /api/v2/tickets$
  #     - /api/v2/users$

  # - namespace: weather
  #   name: OpenWeatherMap API
  #   url: https://gist.githubusercontent.com/mor10/6fb15f2270f8ac1d8b99aa66f9b63410/raw/0e2c4ed43eb4c126ec2284bc7c069de488b53d99/openweatherAPI.json
  #   base_url: https://api.openweathermap.org/data/2.5
  #   paths:
  #     - /data/2.5/weather
'''

[start]
  cmd = "python main.py --config assets/servers.yaml"